CREATE TABLE users (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password TEXT NOT NULL
);
CREATE TABLE budget_infos(
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	userId INTEGER REFERENCES users(id) UNIQUE,
	total INTEGER NOT NULL,
	liabilities INTEGER NOT NULL,
	target_savings INTEGER NOT NULL,
	days INTEGER NOT NULL,
	budgetPerDay INTEGER NOT NULL
);
CREATE TABLE perDayExps (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	userId INTEGER REFERENCES users(id) NOT NULL,
	day VARCHAR(50) NOT NULL,
	expenses INTEGER NOT NULL 
);